# Generated by Django 6.0.7 on 2026-08-04 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ekko_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ansatt',
            options={'ordering': ['username']},
        ),
    ]
