# Generated by Django 6.0.7 on 2026-08-04 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ekko_app', '0002_alter_ansatt_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='ansatt',
            name='is_it_hjelp',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ansatt',
            name='is_vaktleder',
            field=models.BooleanField(default=False),
        ),
    ]
